### ISSUE TITLE
Expose static data via the API

### ISSUE THREAD

**Issue by guillett** [StartupsPoleEmploi/clara#57]
Clara API should serve static data
- input variables
- rules
- aids

**Comment by bdavidxyz** [comment]
Can you provide an example ?

**Comment by guillett** [comment]
- `/variables` that expose https://github.com/StartupsPoleEmploi/clara/blob/master/app/models/variable.rb
- `/aids` for https://github.com/StartupsPoleEmploi/clara/blob/master/app/models/aid.rb
- `/rules` for https://github.com/StartupsPoleEmploi/clara/blob/master/app/models/rule.rb

Currently, what is important to me are the input variables (and details about the structure of the [`for_id`](https://clara.pole-emploi.fr/aides?for_id=NDAscGFzX2luZGVtbmlzZSxub3RfYXBwbGljYWJsZSxhdXRyZXNfY2F0LG5pdmVhdV9pbmZyYV81LHBsdXNfZF91bl9hbixub24sbmlsLG5pbCxuaWwsbmlsLG5pbCxuaWwsbmlsLG5pbCxuaWwsbm9uLG5pbA==) query param).
